### PR TITLE
Adopt JavaScript Standard Style

### PR DESCRIPTION
**Pull request by mightyiam**
This is an experiment. Yet, I'm doing it as properly as I can.

Is the maintainer interested?

I love JavaScript Standard Style.
http://standardjs.com/

### CODE REVIEW

**Comment by mightyiam** [comment]
The goal of this approach is to eventually switch from using `eslint` and all those other packages that I’ve installed, to using only the `standard` package and its `standard` command.

That will be possible after I remove all of the rule overrides that I’ve put in place.

**Comment by mightyiam** [comment]
It seems that this requires dropping support for Node.JS v0.10.

**Comment by danielb2** [comment]
Not really. you have to change a lot more than you've changed. 4 spaces vs 2 spaces etc.

I'm following the hapi styleguideline since I end up doing all hapi work.

https://github.com/hapijs/contrib/blob/master/Style.md

**Comment by danielb2** [comment]
This is mentioned in the README file btw

**Comment by mightyiam** [comment]
If this is merged, you'll have style enforcement in CI. Anyway, my experiment was sufficient.

**Comment by danielb2** [comment]
it's already enforced with the testing tool, `lab`

**Pull request closed without merging**
